public class ArthimaticCalculations {
    public void addition(integer x, integer y){
        integer z = x + y;
        system.debug('sum: ' + z);

    }
    public void sub(integer x, integer y){
        integer z = x - y;
        system.debug('sub: ' + z);
    }
    public void multiplication (integer x, integer y, integer m){
        integer z = x * y * m;
        system.debug('multiplication: ' + z);
    }
    
}

  