public  class checkDataTypes {
   public void methodBoolean(){
    boolean checkBoolean = true;
    system.debug(checkBoolean);

   }
   public void methodInteger(){
    integer varFirst = 1;
    integer varSecond = 2;
    system.debug('var first is => ' + varFirst + ' var second is =>' + varSecond);
 
   }
   public void stringmethod(){
    string varName = 'name';
    string var2Name = 'Fatma';
    system.debug(varName + ': ' + var2Name);
   }
}