public  class MathPractice {
    public decimal practiceThree(decimal a, decimal b){
        decimal sayiOrt = (a + b)/2;
        return sayiOrt;
    }
















    // public decimal practiceOne(Decimal x, Decimal y){
    //     Decimal diktortgenCev = 2*(x + y);
    //     return diktortgenCev;

    
    // public decimal practiceTwo( Decimal k, Decimal b){
    //     decimal kiloBoy = k/(b*b);
    //     return kiloBoy;
    // }
    
}