// public class PrimitiveDataTypeDemo {
//    public void printBasicDataType(){
//     string batchName = ' Batch 13';
//     Integer totalCandidates = 50;
//     Boolean isAdminCompleted = true;
//     string batchDescription = batchName + ' are the best, yess';
//     system.debug(batchDescription);
//     system.debug(' total candidates ' + totalCandidates);

//     Decimal dec = 55.49;
//     system.debug(' decimal value => ' + dec);
//     Long lng = 34253546L;
//     system.debug( 'long value => ' + lng);

//     object obj1 = ' this is string ';
//     object obj2 = 55;
//     object obj3 = true;
//     system.debug('obj1 => ' + obj1);

//     ID conId = ''
//     system.debug('id is ' + conId);


 


//    }
// }
