public  class SalesforceDeveloper {
    public void myFirstCode(){
        string city = 'Istanbul';
        string season = 'spring';
        string movie = 'The Pianist';
        system.debug('my favorite city: ' + city);
        system.debug('my favorite season ' +season );
        system.debug('my favorite movie: ' + movie);
    }

    public void myFavorite (){
        integer num = 5;
        string city = 'Chicago';
        system.debug(num);
        system.debug(city);
        system.debug('my favorite number ==> ' + num + ' my favorite city ==> ' + city);
    }
}
