public  class SOQL_Assignment {
//    public static void soql_WhereClause(){
//     List<Contact> istContact =[select name from contact where name like 'a%'];
//     system.debug('contact name starting a ' +istContact);

//    }
//    public static void soql_FromMethod(){
//     List<Contact> istContact =[select lastName, phone from contact];
//     for(contact eachCountact :istContact){
//         string lastName = eachCountact.lastName;
//         string phone = eachCountact.phone;
//         system.debug('contact last name = ' + lastName);
//         system.debug('contact phone = ' + phone);

//     }
//    }
 
}