// system.debug('name: Fatma');
// system.debug('place of birth: Turkey');
// system.debug('thinks i like: Swiming, Reading, Eating');
// system.debug('place to visit: Spain, Mexico, Switzerland');

string brand = 'Toyota';
string model = 'RAW4';
string color = 'white';
string myCar = brand + ' ' + model + ' ' + color;
system.debug(brand);
system.debug(model);
system.debug(color);
system.debug(myCar);

