 list<integer> listInteger = new list<integer>();
 listInteger.add(10);
    listInteger.add(15);
    listInteger.add(21);
    listInteger.add(15);
    listInteger.add(15);
    integer sum1 = ListDemo.add(listInteger);
    system.debug('sum is = ' + sum1);
  






ListDemo.iterateIntegerList();

ListDemo.allCats();




string c2 = ListDemo.candidatesList(2);
system.debug('c2 ==> ' + c2);
string c5 = ListDemo.candidatesList(5);
system.debug('c5 ==> ' + c5);
ListDemo.randomIntegerList();





